/*
 * This source file was generated by the Gradle 'init' task
 */

import main.controller.Controller


fun main() {

    try {
        val controller = Controller()
        controller.run()
    } catch (error: Exception) {
        error.printStackTrace()
    }
}
